run:
  timeout: 10m
  go: '1.21'
  tests: false

linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - goimports
    - misspell

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment

  goimports:
    local-prefixes: github.com/formatho/agent-todo

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Exclude comments requirements
    - linters:
        - revive
      text: "exported:"
    - linters:
        - revive
      text: "package-comments"
